# .travis.yml

# whitelist
branches:
  only:
    - development
    - master

matrix:
  include:
    - os: osx
      osx_image: xcode7.2
      sudo: required

script:
  - echo ">> Let's build and test the '$TRAVIS_BRANCH' branch for bluemix-objectstore-clientsdk-swift."
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./build/build_package.sh ; fi
  - echo ">> Build and tests completed. See above for status."
