language: objective-c
matrix:
  include:
    - osx_image: xcode8
install:
  - gem install cocoapods --pre
before_script:
  - rm -rf ~/Library/Developer/Xcode/DerivedData
  - pod setup
script:
  - pod install
  - pod lib lint --allow-warnings
  - carthage update
  - xcodebuild clean build -workspace 'BluemixObjectStorage.xcworkspace' -scheme 'BluemixObjectStorage' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
  - xcodebuild test -workspace 'BluemixObjectStorage.xcworkspace' -scheme 'BluemixObjectStorageTests' -destination 'platform=iOS Simulator,name=iPhone 6s'
